name: Publish images

on:
  push:
    branches: [ pages ]

jobs:
  setup:
    name: Build Container image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1

    - name: Login in to docker registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Login in to quay.io registry
      uses: docker/login-action@v1
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_TOKEN }}

    - name: Build the content and push the images
      run: ./scripts/build.sh